version: '3'
services:
  dbpostgresql:
    image: "postgres"
    ports:
      - "5434"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app:
    build: src
    image: appbootrest
    container_name: appbootrest
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"


